[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.build]
cmds = ["echo 'Skipping redundant python3 build phase'"]

[phases.install]
cmds = ["pip install -e ."]

[start]
cmd = "techassist-web"
